alpha: float = 2.5
batch_size: int = 256
buffer_size: int = 10000000
checkpoints_path: str = "./checkpoints/"
device: str = "cuda"
discount: float = 0.99
env: str = "peg_insertion"
eval_freq: int = 5000
expl_noise: float = 0.1
group: str = "td3-bc-peg-insertion"
load_model: str = ''
max_timesteps: int = 1000000
n_episodes: int = 10
name: str = "TD3-BC"
noise_clip: float = 0.5
normalize: bool = True
normalize_reward: bool = False
policy_freq: int = 1
policy_noise: float = 0.2
project: str = "CORL"
seed: int = 0
tau: float = 0.005